In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("/content/Ecommerce_Order_Test_Dataset.csv")

In [5]:
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,upi,5,1470.84,0.05,4.4
1,ORD0002,02-01-2025,05-01-2025,Customer_001,Male,Delhi,Books,Data Science Guide,Debit Card,3,2114.91,0.20,3.0
2,ORD0003,04-01-2025,06-01-2025,Customer_047,male,Mumbai,Electronics,Keyboard,Cash,3,3053.63,0.20,3.3
3,ORD0004,06-01-2025,09-01-2025,Customer_034,Female,Chennai,Clothing,Sneakers,Debit Card,2,1427.69,0.00,3.6
4,ORD0005,08-01-2025,15-01-2025,Customer_032,Female,Coimbatore,Clothing,Jeans,UPI,4,752.61,0.20,3.8

In [6]:
df.shape

(101, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       101 non-null    object
 1   Order_Date     101 non-null    object
 2   Delivery_Date  101 non-null    object
 3   Customer_Name  100 non-null    object
 4   Gender         101 non-null    object
 5   City           100 non-null    object
 6   Category       101 non-null    object
 7   Product        101 non-null    object
 8   Payment_Mode   100 non-null    object
 9   Quantity       101 non-null    int64
 10  Unit_Price     100 non-null    float64
 11  Discount       101 non-null    float64
 12  Rating         100 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 10.4+ KB

In [8]:
df.describe()

         Quantity   Unit_Price    Discount      Rating
count  101.000000   100.000000  101.000000  100.000000
mean     3.168317  2579.265200    0.092079    3.738000
std      1.456498  1375.131202    0.070969    0.687813
min      1.000000   166.990000    0.000000    2.600000
25%      2.000000  1441.565000    0.050000    3.100000
50%      3.000000  2691.975000    0.100000    3.750000
75%      4.000000  3783.245000    0.150000    4.400000
max      5.000000  4927.900000    0.200000    5.000000

In [9]:
print(df.isnull().sum())

Order_ID         0
Order_Date       0
Delivery_Date    0
Customer_Name    1
Gender           0
City             1
Category         0
Product          0
Payment_Mode     1
Quantity         0
Unit_Price       1
Discount         0
Rating           1
dtype: int64

In [10]:
df["City"] = df["City"].fillna("Unknown")
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")
df["Rating"] = df["Rating"].fillna(df["Rating"].mean())
df["Payment_Mode"] = df["Payment_Mode"].fillna("Unknown")

In [11]:
print("Duplicates:", df.duplicated().sum())

Duplicates: 1

In [12]:
df = df.drop_duplicates()

print("New Shape:", df.shape)

New Shape: (100, 13)

In [13]:
df["Gender"] = df["Gender"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()
df["Payment_Mode"] = df["Payment_Mode"].str.strip().str.title()

In [14]:
print(df["Gender"].unique())
print(df["City"].unique())
print(df["Payment_Mode"].unique())

['Male' 'Female']
['Mumbai' 'Delhi' 'Chennai' 'Coimbatore' 'Madurai' 'Unknown' 'Pune'
 'Hyderabad' 'Bengaluru']
['Upi' 'Debit Card' 'Cash' 'Credit Card' 'Unknown']

In [15]:
df["Total Price"] = df["Quantity"] * df["Unit_Price"]

df["Discount Amount"] = df["Total Price"] * df["Discount"]

df["Final Amount"] = df["Total Price"] - df["Discount Amount"]

print(df[["Order_ID", "Product", "Quantity",
          "Total Price", "Discount Amount", "Final Amount"]])

   Order_ID             Product  Quantity  Total Price  Discount Amount  \
0   ORD0001              Jacket         5      7354.20          367.710
1   ORD0002  Data Science Guide         3      6344.73         1268.946
2   ORD0003            Keyboard         3      9160.89         1832.178
3   ORD0004            Sneakers         2      2855.38            0.000
4   ORD0005               Jeans         4      3010.44          602.088
..      ...                 ...       ...          ...              ...
95  ORD0096          Table Lamp         5     24341.20         1217.060
96  ORD0097          Table Lamp         1      3049.48          304.948
97  ORD0098          Exam Guide         4      4787.44          239.372
98  ORD0099        Water Bottle         3     12380.31         1238.031
99  ORD0100          Headphones         1      1790.90          358.180

    Final Amount
0       6986.490
1       5075.784
2       7328.712
3       2855.380
4       2408.352
..           ...
95     23124.140
96      2744.532
97      4548.068
98     11142.279
99      1432.720

[100 rows x 6 columns]

In [16]:
print("Total Quantity:", df["Quantity"].sum())

print("Average Unit Price:", df["Unit_Price"].mean())

print("Maximum Unit Price:", df["Unit_Price"].max())

print("Minimum Unit Price:", df["Unit_Price"].min())

print("Average Rating:", df["Rating"].mean())

Total Quantity: 315
Average Unit Price: 2600.2126262626257
Maximum Unit Price: 4927.9
Minimum Unit Price: 166.99
Average Rating: 3.74638

In [26]:
columns = ["Order_ID", "Product", "Quantity", "Rating",
           "Final Amount", "City"]

In [27]:
print(df[df["Quantity"] > 3][columns])

   Order_ID        Product  Quantity  Rating  Final Amount        City
0   ORD0001         Jacket         5   4.400     6986.4900      Mumbai
4   ORD0005          Jeans         4   3.800     2408.3520  Coimbatore
8   ORD0009          Jeans         4   3.200    11201.2600        Pune
10  ORD0011       Sneakers         5   2.900     2400.9825      Mumbai
11  ORD0012         Jacket         5   3.700    17582.5600      Mumbai
18  ORD0019     Exam Guide         5   3.300     7784.0800       Delhi
19  ORD0020        T-Shirt         5   3.738    18864.6500      Mumbai
20  ORD0021        Cushion         5   3.100     9621.8375   Hyderabad
22  ORD0023     Table Lamp         5   4.400    14442.5000        Pune
24  ORD0025  Python Basics         4   3.700     1009.5480   Bengaluru
27  ORD0028   Water Bottle         5   4.800     2228.9850        Pune
28  ORD0029     Exam Guide         4   4.600    11863.9600     Chennai
29  ORD0030     Exam Guide         4   4.900    10329.5400     Madurai
30  ORD0031      USB Cable         4   2.800    12078.5920        Pune
32  ORD0033  Python Basics         5   4.800    13352.5350  Coimbatore
33  ORD0034   Water Bottle         4   3.000    13168.7640  Coimbatore
39  ORD0040        T-Shirt         5   4.500     6869.4025       Delhi
40  ORD0041       Sneakers         5   3.000     5019.3900   Bengaluru
42  ORD0043        Cushion         4   2.900    15237.2000  Coimbatore
44  ORD0045     Exam Guide         4   4.200     4816.1000      Mumbai
45  ORD0046          Novel         4   3.800      793.0980        Pune
46  ORD0047          Novel         5   3.400    12705.0500     Chennai
50  ORD0051         Jacket         5   3.600    20501.4500        Pune
51  ORD0052    Storage Box         4   3.400    19372.2800     Chennai
53  ORD0054          Novel         4   3.300    13531.6940     Madurai
57  ORD0058       Keyboard         5   4.700    17751.9150        Pune
59  ORD0060      USB Cable         4   3.900    12943.1040   Hyderabad
60  ORD0061         Jacket         5   4.800    21495.8400     Chennai
61  ORD0062        T-Shirt         5   4.100    13279.5075        Pune
62  ORD0063      USB Cable         5   2.800    23295.2825     Madurai
63  ORD0064      USB Cable         5   4.800    15398.1500     Chennai
64  ORD0065          Jeans         5   4.100    13683.1300   Hyderabad
66  ORD0067     Exam Guide         4   2.800     2074.4580  Coimbatore
67  ORD0068     Headphones         5   4.500    18296.7500       Delhi
68  ORD0069          Novel         4   4.100     8903.9680      Mumbai
71  ORD0072   Water Bottle         4   4.500     5928.0000       Delhi
77  ORD0078          Novel         5   3.900    19338.5000        Pune
81  ORD0082          Novel         4   4.600     6488.3880  Coimbatore
83  ORD0084          Novel         4   4.600    10585.0080      Mumbai
84  ORD0085        T-Shirt         4   2.800     6385.1760   Bengaluru
85  ORD0086        T-Shirt         5   3.500    10930.3600   Hyderabad
87  ORD0088     Headphones         4   2.900    11268.3300     Madurai
88  ORD0089          Novel         4   3.100     7008.9980     Chennai
91  ORD0092          Novel         4   4.100    11943.7240   Hyderabad
93  ORD0094    Storage Box         4   3.900    15782.9760   Bengaluru
94  ORD0095    Storage Box         4   3.100    10498.6400   Bengaluru
95  ORD0096     Table Lamp         5   3.400    23124.1400  Coimbatore
97  ORD0098     Exam Guide         4   4.800     4548.0680      Mumbai

In [28]:
print(df[df["Rating"] >= 4.5][columns])

   Order_ID             Product  Quantity  Rating  Final Amount        City
17  ORD0018  Data Science Guide         2     5.0     8870.2200     Madurai
27  ORD0028        Water Bottle         5     4.8     2228.9850        Pune
28  ORD0029          Exam Guide         4     4.6    11863.9600     Chennai
29  ORD0030          Exam Guide         4     4.9    10329.5400     Madurai
32  ORD0033       Python Basics         5     4.8    13352.5350  Coimbatore
37  ORD0038      Wireless Mouse         3     4.6     2651.3280        Pune
39  ORD0040             T-Shirt         5     4.5     6869.4025       Delhi
43  ORD0044          Exam Guide         2     4.5      527.6640     Chennai
47  ORD0048              Jacket         1     4.7     2433.4300     Chennai
49  ORD0050             Cushion         3     4.5     4100.6805   Hyderabad
57  ORD0058            Keyboard         5     4.7    17751.9150        Pune
60  ORD0061              Jacket         5     4.8    21495.8400     Chennai
63  ORD0064           USB Cable         5     4.8    15398.1500     Chennai
67  ORD0068          Headphones         5     4.5    18296.7500       Delhi
70  ORD0071             Cushion         3     4.7    12999.7335        Pune
71  ORD0072        Water Bottle         4     4.5     5928.0000       Delhi
79  ORD0080               Novel         1     4.7      259.7760   Bengaluru
81  ORD0082               Novel         4     4.6     6488.3880  Coimbatore
83  ORD0084               Novel         4     4.6    10585.0080      Mumbai
86  ORD0087          Table Lamp         2     4.5     4002.7860     Chennai
97  ORD0098          Exam Guide         4     4.8     4548.0680      Mumbai

In [29]:
print(df[df["Final Amount"] > 5000][columns])

   Order_ID             Product  Quantity  Rating  Final Amount        City
0   ORD0001              Jacket         5   4.400     6986.4900      Mumbai
1   ORD0002  Data Science Guide         3   3.000     5075.7840       Delhi
2   ORD0003            Keyboard         3   3.300     7328.7120      Mumbai
6   ORD0007            Keyboard         2   2.800     8004.6370       Delhi
8   ORD0009               Jeans         4   3.200    11201.2600        Pune
11  ORD0012              Jacket         5   3.700    17582.5600      Mumbai
12  ORD0013            Sneakers         2   3.800     5045.0040     Madurai
15  ORD0016           USB Cable         3   2.800    11730.7500     Madurai
17  ORD0018  Data Science Guide         2   5.000     8870.2200     Madurai
18  ORD0019          Exam Guide         5   3.300     7784.0800       Delhi
19  ORD0020             T-Shirt         5   3.738    18864.6500      Mumbai
20  ORD0021             Cushion         5   3.100     9621.8375   Hyderabad
21  ORD0022      Wireless Mouse         3   4.200    10615.3950   Hyderabad
22  ORD0023          Table Lamp         5   4.400    14442.5000        Pune
28  ORD0029          Exam Guide         4   4.600    11863.9600     Chennai
29  ORD0030          Exam Guide         4   4.900    10329.5400     Madurai
30  ORD0031           USB Cable         4   2.800    12078.5920        Pune
31  ORD0032      Wireless Mouse         3   4.300    13037.3535  Coimbatore
32  ORD0033       Python Basics         5   4.800    13352.5350  Coimbatore
33  ORD0034        Water Bottle         4   3.000    13168.7640  Coimbatore
34  ORD0035         Storage Box         3   2.700    10286.1900  Coimbatore
39  ORD0040             T-Shirt         5   4.500     6869.4025       Delhi
40  ORD0041            Sneakers         5   3.000     5019.3900   Bengaluru
41  ORD0042             T-Shirt         2   2.900     7925.9040      Mumbai
42  ORD0043             Cushion         4   2.900    15237.2000  Coimbatore
46  ORD0047               Novel         5   3.400    12705.0500     Chennai
50  ORD0051              Jacket         5   3.600    20501.4500        Pune
51  ORD0052         Storage Box         4   3.400    19372.2800     Chennai
53  ORD0054               Novel         4   3.300    13531.6940     Madurai
57  ORD0058            Keyboard         5   4.700    17751.9150        Pune
58  ORD0059             T-Shirt         2   3.500     6465.7400       Delhi
59  ORD0060           USB Cable         4   3.900    12943.1040   Hyderabad
60  ORD0061              Jacket         5   4.800    21495.8400     Chennai
61  ORD0062             T-Shirt         5   4.100    13279.5075        Pune
62  ORD0063           USB Cable         5   2.800    23295.2825     Madurai
63  ORD0064           USB Cable         5   4.800    15398.1500     Chennai
64  ORD0065               Jeans         5   4.100    13683.1300   Hyderabad
65  ORD0066        Water Bottle         3   3.300     7610.2200   Bengaluru
67  ORD0068          Headphones         5   4.500    18296.7500       Delhi
68  ORD0069               Novel         4   4.100     8903.9680      Mumbai
69  ORD0070          Table Lamp         3   3.800     5889.1230   Hyderabad
70  ORD0071             Cushion         3   4.700    12999.7335        Pune
71  ORD0072        Water Bottle         4   4.500     5928.0000       Delhi
73  ORD0074             Cushion         2   3.300     6333.2100       Delhi
77  ORD0078               Novel         5   3.900    19338.5000        Pune
81  ORD0082               Novel         4   4.600     6488.3880  Coimbatore
83  ORD0084               Novel         4   4.600    10585.0080      Mumbai
84  ORD0085             T-Shirt         4   2.800     6385.1760   Bengaluru
85  ORD0086             T-Shirt         5   3.500    10930.3600   Hyderabad
87  ORD0088          Headphones         4   2.900    11268.3300     Madurai
88  ORD0089               Novel         4   3.100     7008.9980     Chennai
89  ORD0090          Table Lamp         2   4.300     5981.5690       Delhi
91  ORD0092               Novel         4   4.100    11943.7240   Hyderabad
93  ORD0094         Storage Box         4   3.900    15782.9760   Bengaluru
94  ORD0095         Storage Box         4   3.100    10498.6400   Bengaluru
95  ORD0096          Table Lamp         5   3.400    23124.1400  Coimbatore
98  ORD0099        Water Bottle         3   4.000    11142.2790     Madurai

In [30]:
print(df[df["City"] == "Chennai"][columns])

   Order_ID       Product  Quantity  Rating  Final Amount     City
3   ORD0004      Sneakers         2     3.6      2855.380  Chennai
28  ORD0029    Exam Guide         4     4.6     11863.960  Chennai
43  ORD0044    Exam Guide         2     4.5       527.664  Chennai
46  ORD0047         Novel         5     3.4     12705.050  Chennai
47  ORD0048        Jacket         1     4.7      2433.430  Chennai
48  ORD0049  Water Bottle         1     3.5      3965.034  Chennai
51  ORD0052   Storage Box         4     3.4     19372.280  Chennai
54  ORD0055       T-Shirt         1     4.4      2990.780  Chennai
60  ORD0061        Jacket         5     4.8     21495.840  Chennai
63  ORD0064     USB Cable         5     4.8     15398.150  Chennai
74  ORD0075     USB Cable         1     3.1      3202.168  Chennai
76  ORD0077         Novel         1     2.6      4226.250  Chennai
78  ORD0079       T-Shirt         3     4.4      1018.944  Chennai
86  ORD0087    Table Lamp         2     4.5      4002.786  Chennai
88  ORD0089         Novel         4     3.1      7008.998  Chennai
90  ORD0091         Novel         2     4.3      1768.194  Chennai
92  ORD0093  Water Bottle         2     4.2      4234.280  Chennai

In [31]:
df_sorted = df.sort_values("Final Amount", ascending=False)

In [32]:
print(df_sorted.head(5))

   Order_ID  Order_Date Delivery_Date Customer_Name  Gender        City  \
62  ORD0063  23-04-2025    27-04-2025  Customer_056    Male     Madurai
95  ORD0096  22-06-2025    29-06-2025  Customer_013    Male  Coimbatore
60  ORD0061  20-04-2025    21-04-2025  Customer_032    Male     Chennai
50  ORD0051  01-04-2025    07-04-2025  Customer_054  Female        Pune
51  ORD0052  03-04-2025    04-04-2025  Customer_005  Female     Chennai

       Category      Product Payment_Mode  Quantity  Unit_Price  Discount  \
62  Electronics    USB Cable          Upi         5     4904.27      0.05
95         Home   Table Lamp          Upi         5     4868.24      0.05
60     Clothing       Jacket          Upi         5     4525.44      0.05
50     Clothing       Jacket         Cash         5     4100.29      0.00
51         Home  Storage Box          Upi         4     4843.07      0.00

    Rating  Total Price  Discount Amount  Final Amount
62     2.8     24521.35        1226.0675    23295.2825
95     3.4     24341.20        1217.0600    23124.1400
60     4.8     22627.20        1131.3600    21495.8400
50     3.6     20501.45           0.0000    20501.4500
51     3.4     19372.28           0.0000    19372.2800

In [33]:
print(df_sorted[[
    "Order_ID",
    "Product",
    "Category",
    "Quantity",
    "Final Amount"
]].head(5))

   Order_ID      Product     Category  Quantity  Final Amount
62  ORD0063    USB Cable  Electronics         5    23295.2825
95  ORD0096   Table Lamp         Home         5    23124.1400
60  ORD0061       Jacket     Clothing         5    21495.8400
50  ORD0051       Jacket     Clothing         5    20501.4500
51  ORD0052  Storage Box         Home         4    19372.2800